# Generated by Django 3.2.6 on 2021-08-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='abb',
        ),
        migrations.AlterField(
            model_name='city',
            name='abb',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.city'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel',
            field=models.CharField(max_length=100),
        ),
    ]
